version: '3'

services:
  db:
    env_file:
      - .env
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - mynetwork

  web:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile-django
    command: >
      bash -c "python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/api
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
