# Generated by Django 4.2.10 on 2024-02-23 19:57

from django.db import migrations
import json
from pathlib import Path

def load_data(apps, schema_editor):
    Book = apps.get_model('api', 'Book')
    file_path = Path(__file__).resolve().parent / 'initial_data.json'
    with open(file_path, 'r') as file:
        data = json.load(file)
        for item in data:
            Book.objects.create(**item)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data),
    ]
